# Generated by Django 2.2.2 on 2019-07-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.TextField(unique=True)),
                ('currently_running', models.BooleanField(default=False)),
            ],
        ),
    ]
