# Generated by Django 2.2.2 on 2019-07-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_notificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationToken',
        ),
    ]
