# Generated by Django 2.2.2 on 2019-08-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_report_usertoreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_addressed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
