# Generated by Django 2.2.2 on 2019-08-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20190805_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_date',
            new_name='report_created',
        ),
    ]
