# Generated by Django 2.2.2 on 2019-06-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanvasWrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
