# Generated by Django 2.2.2 on 2019-06-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanvasWrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashed_token',
            field=models.CharField(max_length=65),
        ),
    ]
