# Generated by Django 2.2.2 on 2019-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanvasWrapper', '0002_auto_20190618_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data',
            field=models.TextField(),
        ),
    ]
