# Generated by Django 2.2.2 on 2019-07-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanvasWrapper', '0002_tempresultsstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempresultsstore',
            name='task_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
