# Generated by Django 2.2.2 on 2019-07-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanvasWrapper', '0003_auto_20190715_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempresultsstore',
            name='ready_to_view',
            field=models.BooleanField(default=False),
        ),
    ]
