# Generated by Django 2.2.2 on 2019-07-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanvasWrapper', '0005_auto_20190715_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queuer',
        ),
    ]
