# Generated by Django 2.2.2 on 2019-07-31 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanvasWrapper', '0006_delete_queuer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertodataset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
