# Generated by Django 2.2.2 on 2019-08-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanvasWrapper', '0008_report_usertoreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoreport',
            name='report',
        ),
        migrations.RemoveField(
            model_name='usertoreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='UserToReport',
        ),
    ]
