# Generated by Django 2.2.2 on 2019-06-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=65, unique=True)),
                ('client_id', models.CharField(max_length=15)),
                ('client_secret', models.CharField(max_length=65)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
    ]
